language: python
python:
    - "2.7"
env:
  - CKANVERSION=master
  - CKANVERSION=2.3
  - CKANVERSION=2.4
  - CKANVERSION=2.5
  - CKANVERSION=2.6
  - CKANVERSION=2.7
  - CKANVERSION=2.8
services:
  - redis-server
  - postgresql
install:
  - bash bin/travis-build.bash
  - pip install coveralls
  - pip install flake8
script: sh bin/travis-run.sh
after_success:
    - coveralls

# the new trusty images of Travis cause build errors with psycopg2, see https://github.com/travis-ci/travis-ci/issues/8897
dist: trusty
group: deprecated-2017Q4

jobs:
  include:
    - stage: Flake8
      env: FLAKE8=True
      script:
         - flake8 --version
         # stop the build if there are Python syntax errors or undefined names
         - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
         # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
         - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
